"""Power block hydraulic flow network solver (Type 6030)."""

import numpy as np

from esclab.simulate import Component


class PBHydraulicSolver(Component):
    """
    Object: PB-HydraulicSolver
    Simulation Studio Model: PB-HydraulicModel

    Flow network diagram:

                           m_dot_in, P_in, T_in,
                            f1     |   (1-f1)
                       -----------------------
                        |                      |
                M_DOT_2 |                      | M_DOT_3
                    f2  | (1-f2)               |
               -----------------               |
                |               |              |
        M_DOT_4 |               | M_DOT_5      |
            f3  |   (1-f3)      |              |
       -----------------        |              |
    SH |               |        |              |
M_DOT_6|       M_DOT_7 |        |              |
    P2 |           P3  |        |              |
       -----------------        |              |
            f4  |   (1-f4)      |              |
        ----------------        |              |
    PH  |               |       |              |
    P4  |           P5  |       |              |
M_DOT_8 |       M_DOT_9 |       |              |
        ----------------        |              |
                |           P6  |              |
                -----------------              |
                        |                   P7 |
                        ------------------------
                                |

    (Comments and routine interface generated by TRNSYS Simulation Studio)
    """

    # PARAMETERS
    Fluid_ID = Component.Parameter()        # FLUID ID Number to select the fluid from SAM Properties (DowthermA = 40)
    m_guess = Component.Parameter()         # guess mass flow entering hydraulic network
    ff1_guess = Component.Parameter()       # guess flow fraction through tee 1
    ff2_guess = Component.Parameter()       # guess flow fraction through tee 2
    ff3_guess = Component.Parameter()       # guess flow fraction through tee 3
    ff4_guess = Component.Parameter()       # guess flow fraction through tee 4
    LR = Component.Parameter()              # learning rate used through system

    # INPUTS
    m_dot_in = Component.Input()            # Mass into the system
    m_dot_2_in = Component.Input()
    m_dot_3_in = Component.Input()
    m_dot_4_in = Component.Input()
    m_dot_5_in = Component.Input()
    m_dot_6_in = Component.Input()
    m_dot_7_in = Component.Input()
    m_dot_8_in = Component.Input()
    m_dot_9_in = Component.Input()
    P_in = Component.Input()                # Pressure into the system
    P2 = Component.Input()
    P3 = Component.Input()
    P4 = Component.Input()
    P5 = Component.Input()
    P6 = Component.Input()
    P7 = Component.Input()
    T_in = Component.Input()                # Temperature into the system

    # OUTPUTS
    m_dot_2 = Component.Output()            # m_dot_2
    m_dot_3 = Component.Output()            # m_dot_3
    m_dot_4 = Component.Output()            # m_dot_4
    m_dot_5 = Component.Output()            # m_dot_5
    m_dot_6 = Component.Output()            # m_dot_6
    m_dot_7 = Component.Output()            # m_dot_7
    m_dot_8 = Component.Output()            # m_dot_8
    m_dot_9 = Component.Output()            # m_dot_9
    f1 = Component.Output()                 # flowfraction into 1st tee
    f2 = Component.Output()                 # flowfraction into 2nd tee
    f3 = Component.Output()                 # flowfraction into 3rd tee
    f4 = Component.Output()                 # flowfraction into 4th tee

    def presim_setup(self, **kwargs):
        super().presim_setup(**kwargs)

        flow_min = 0.000000001

        if self.m_guess.v <= 0.0:
            self.m_guess.v = 10.0  # use this as an initial guess

        # Tee 1 initial guesses
        if self.ff1_guess.v != 1.0:
            if self.ff1_guess.v != 0.0:
                m_dot_2 = self.m_guess.v * self.ff1_guess.v
                m_dot_3 = self.m_guess.v * (1.0 - self.ff1_guess.v)
            else:  # ff1_guess == 0.0, send minimum flow through branch 1 and max through branch 2
                m_dot_2 = flow_min
                m_dot_3 = self.m_guess.v - flow_min
        else:
            m_dot_3 = flow_min
            m_dot_2 = self.m_guess.v - flow_min

        # Tee 2 initial guesses
        if self.ff2_guess.v != 1.0:
            if self.ff2_guess.v != 0.0:
                m_dot_4 = m_dot_2 * self.ff2_guess.v
                m_dot_5 = m_dot_2 * (1.0 - self.ff2_guess.v)
            else:  # ff2_guess == 0.0, send minimum flow through branch 1 and max through branch 2
                m_dot_4 = flow_min
                m_dot_5 = m_dot_2 - flow_min
        else:
            m_dot_5 = flow_min
            m_dot_4 = m_dot_2 - flow_min

        # Tee 3 initial guesses
        if self.ff3_guess.v != 1.0:
            if self.ff3_guess.v != 0.0:
                m_dot_6 = m_dot_4 * self.ff3_guess.v
                m_dot_7 = m_dot_4 * (1.0 - self.ff3_guess.v)
            else:  # ff3_guess == 0.0, send minimum flow through branch 1 and max through branch 2
                m_dot_6 = flow_min
                m_dot_7 = m_dot_4 - flow_min
        else:
            m_dot_7 = flow_min
            m_dot_6 = m_dot_4 - flow_min

        # Tee 4 initial guesses
        if self.ff4_guess.v != 1.0:
            if self.ff4_guess.v != 0.0:
                m_dot_8 = m_dot_4 * self.ff4_guess.v
                m_dot_9 = m_dot_4 * (1.0 - self.ff4_guess.v)
            else:  # ff2_guess == 0.0, send minimum flow through branch 1 and max through branch 2
                m_dot_8 = flow_min
                m_dot_9 = m_dot_4 - flow_min
        else:
            m_dot_9 = flow_min
            m_dot_8 = m_dot_4 - flow_min

        # Set the Initial Values of the Outputs (#,Value)
        self.m_dot_2.v = m_dot_2        # m_dot_2
        self.m_dot_3.v = m_dot_3        # m_dot_3
        self.m_dot_4.v = m_dot_4        # m_dot_4
        self.m_dot_5.v = m_dot_5        # m_dot_5
        self.m_dot_6.v = m_dot_6        # m_dot_6
        self.m_dot_7.v = m_dot_7        # m_dot_7
        self.m_dot_8.v = m_dot_8        # m_dot_8
        self.m_dot_9.v = m_dot_9        # m_dot_9
        self.f1.v = self.ff1_guess.v    # flowfraction into 1st tee
        self.f2.v = self.ff2_guess.v    # flowfraction into 2nd tee
        self.f3.v = self.ff3_guess.v    # flowfraction into 3rd tee
        self.f4.v = self.ff4_guess.v    # flowfraction into 4th tee

        return

    def calculate(self):
        super().calculate()

        flow_min = 0.000000001

        # Read inputs into local working variables
        m_dot_2 = self.m_dot_2_in.v
        m_dot_3 = self.m_dot_3_in.v
        m_dot_4 = self.m_dot_4_in.v
        m_dot_5 = self.m_dot_5_in.v
        m_dot_6 = self.m_dot_6_in.v
        m_dot_7 = self.m_dot_7_in.v
        m_dot_8 = self.m_dot_8_in.v
        m_dot_9 = self.m_dot_9_in.v

        if (self.model.timestep_iteration > 0) or (self.model.time > self.model.timestep):

            tol = 0.0001
            err = 1.0
            iter_count = 1
            max_iter = 3

            while (err > tol) and (iter_count <= max_iter):

                # Find the loss coefficient, K, for each the piping line based on the pressure drop down the pipe
                # and the mass flow rate going through it
                K3 = abs((self.P_in.v - abs(self.P7.v)) / (m_dot_3 ** 2.0))
                K5 = abs((self.P_in.v - abs(self.P6.v)) / (m_dot_5 ** 2.0))
                K6 = abs((self.P_in.v - abs(self.P2.v)) / (m_dot_6 ** 2.0))
                K7 = abs((self.P_in.v - abs(self.P3.v)) / (m_dot_7 ** 2.0))
                K8 = abs((self.P2.v - abs(self.P4.v)) / (m_dot_8 ** 2.0))
                K9 = abs((self.P2.v - abs(self.P5.v)) / (m_dot_9 ** 2.0))

                # Update A matrix with new loss coefficients
                A = np.zeros((9, 9))

                # Mass Continuity Equations
                A[0, 0] = 1.0
                A[1, 0] = -1.0
                A[1, 1] = 1.0
                A[1, 2] = 1.0
                A[2, 1] = -1.0
                A[2, 3] = 1.0
                A[2, 4] = 1.0
                A[3, 3] = -1.0
                A[3, 5] = 1.0
                A[3, 6] = 1.0
                A[4, 3] = -1.0
                A[4, 7] = 1.0
                A[4, 8] = 1.0

                # Constant Pressure Drop Equations
                k3_hat = K3 * abs(m_dot_3)
                k5_hat = K5 * abs(m_dot_5)
                k6_hat = K6 * abs(m_dot_6)
                k7_hat = K7 * abs(m_dot_7)
                k8_hat = K8 * abs(m_dot_8)
                k9_hat = K9 * abs(m_dot_9)

                A[5, 5] = k6_hat
                A[5, 6] = -k7_hat

                A[6, 7] = k8_hat
                A[6, 8] = -k9_hat

                # Adjust 8th equation based on where the flow is going
                if m_dot_4 > 0.001:
                    A[7, 2] = -k3_hat
                    A[7, 5] = k6_hat
                    A[7, 7] = k8_hat
                else:
                    if m_dot_5 > 0.001:  # compare reheater and SGT bypass branch together
                        A[7, 2] = -k3_hat
                        A[7, 4] = k5_hat
                    else:
                        A[7, 2] = -k3_hat
                        A[7, 5] = k6_hat
                        A[7, 7] = k8_hat

                A[8, 4] = -k5_hat
                A[8, 5] = k6_hat
                A[8, 7] = k8_hat

                # Set up b array
                b = np.zeros(9)
                b[0] = self.m_dot_in.v

                # Solve the linear system A*x = b using numpy
                # (replaces Call matrixinv(A, A_inv, 9) + x = matmul(A_inv, b) from Fortran)
                x = np.linalg.solve(A, b)

                if (self.model.timestep_iteration != 1) or (self.model.time != self.model.timestep):

                    if x[1] < 0.001:
                        x[1] = max(flow_min, x[1])
                        m_dot_2 = max(flow_min, m_dot_2)
                        m_hold = np.log10(m_dot_2) * (1.0 - self.LR.v) + np.log10(x[1]) * self.LR.v
                        m_dot_2 = 10 ** m_hold
                    else:
                        m_dot_2 = m_dot_2 + (x[1] - m_dot_2) * self.LR.v

                    if x[2] < 0.001:
                        x[2] = max(flow_min, x[2])
                        m_dot_3 = max(flow_min, m_dot_3)
                        m_hold = np.log10(m_dot_3) * (1.0 - self.LR.v) + np.log10(x[2]) * self.LR.v
                        m_dot_3 = 10 ** m_hold
                    else:
                        m_dot_3 = m_dot_3 + (x[2] - m_dot_3) * self.LR.v

                    if x[3] < 0.001:
                        x[3] = max(flow_min, x[3])
                        m_dot_4 = max(flow_min, m_dot_4)
                        m_hold = np.log10(m_dot_4) * (1.0 - self.LR.v) + np.log10(x[3]) * self.LR.v
                        m_dot_4 = 10 ** m_hold
                    else:
                        m_dot_4 = m_dot_4 + (x[3] - m_dot_4) * self.LR.v

                    if x[4] < 0.001:
                        x[4] = max(flow_min, x[4])
                        m_dot_5 = max(flow_min, m_dot_5)
                        m_hold = np.log10(m_dot_5) * (1.0 - self.LR.v) + np.log10(x[4]) * self.LR.v
                        m_dot_5 = 10 ** m_hold
                    else:
                        m_dot_5 = m_dot_5 + (x[4] - m_dot_5) * self.LR.v

                    if x[5] < 0.001:
                        x[5] = max(flow_min, x[5])
                        m_dot_6 = max(flow_min, m_dot_6)
                        m_hold = np.log10(m_dot_6) * (1.0 - self.LR.v) + np.log10(x[5]) * self.LR.v
                        m_dot_6 = 10 ** m_hold
                    else:
                        m_dot_6 = m_dot_6 + (x[5] - m_dot_6) * self.LR.v

                    if x[6] < 0.001:
                        x[6] = max(flow_min, x[6])
                        m_dot_7 = max(flow_min, m_dot_7)
                        m_hold = np.log10(m_dot_7) * (1.0 - self.LR.v) + np.log10(x[6]) * self.LR.v
                        m_dot_7 = 10 ** m_hold
                    else:
                        m_dot_7 = m_dot_7 + (x[6] - m_dot_7) * self.LR.v

                    if x[7] < 0.001:
                        x[7] = max(flow_min, x[7])
                        m_dot_8 = max(flow_min, m_dot_8)
                        m_hold = np.log10(m_dot_8) * (1.0 - self.LR.v) + np.log10(x[7]) * self.LR.v
                        m_dot_8 = 10 ** m_hold
                    else:
                        m_dot_8 = m_dot_8 + (x[7] - m_dot_8) * self.LR.v

                    if x[8] < 0.001:
                        x[8] = max(flow_min, x[8])
                        m_dot_9 = max(flow_min, m_dot_9)
                        m_hold = np.log10(m_dot_9) * (1.0 - self.LR.v) + np.log10(x[8]) * self.LR.v
                        m_dot_9 = 10 ** m_hold
                    else:
                        m_dot_9 = m_dot_9 + (x[8] - m_dot_9) * self.LR.v

                else:
                    m_dot_2 = m_dot_2 + (x[1] - m_dot_2) * self.LR.v
                    m_dot_3 = m_dot_3 + (x[2] - m_dot_3) * self.LR.v
                    m_dot_4 = m_dot_4 + (x[3] - m_dot_4) * self.LR.v
                    m_dot_5 = m_dot_5 + (x[4] - m_dot_5) * self.LR.v
                    m_dot_6 = m_dot_6 + (x[5] - m_dot_6) * self.LR.v
                    m_dot_7 = m_dot_7 + (x[6] - m_dot_7) * self.LR.v
                    m_dot_8 = m_dot_8 + (x[7] - m_dot_8) * self.LR.v
                    m_dot_9 = m_dot_9 + (x[8] - m_dot_9) * self.LR.v

                # TODO-NEEDS CONVERSION REVIEW: Fortran writes
                # err = sqrt(m_dot_2-x(2,1))**2 + sqrt(m_dot_3-x(3,1))**2 + ...
                # sqrt(a)**2 simplifies to a only when a >= 0; this appears to be a bug in the
                # original code (likely intent was (m_dot_i - x_i)**2). Ported faithfully as written.
                err = (np.sqrt(m_dot_2 - x[1])) ** 2 + (np.sqrt(m_dot_3 - x[2])) ** 2 + \
                      (np.sqrt(m_dot_4 - x[3])) ** 2 + (np.sqrt(m_dot_5 - x[4])) ** 2 + \
                      (np.sqrt(m_dot_6 - x[5])) ** 2 + (np.sqrt(m_dot_7 - x[6])) ** 2 + \
                      (np.sqrt(m_dot_8 - x[7])) ** 2 + (np.sqrt(m_dot_9 - x[8])) ** 2
                iter_count += 1

        if (self.model.timestep_iteration == 0) or (self.model.time == self.model.timestep):
            m_dot_2 = self.m_dot_2.v
            m_dot_3 = self.m_dot_3.v
            m_dot_4 = self.m_dot_4.v
            m_dot_5 = self.m_dot_5.v
            m_dot_6 = self.m_dot_6.v
            m_dot_7 = self.m_dot_7.v
            m_dot_8 = self.m_dot_8.v
            m_dot_9 = self.m_dot_9.v

        # Set the Outputs from this Model (#,Value)
        self.m_dot_2.v = m_dot_2                                # m_dot_2
        self.m_dot_3.v = m_dot_3                                # m_dot_3
        self.m_dot_4.v = m_dot_4                                # m_dot_4
        self.m_dot_5.v = m_dot_5                                # m_dot_5
        self.m_dot_6.v = m_dot_6                                # m_dot_6
        self.m_dot_7.v = m_dot_7                                # m_dot_7
        self.m_dot_8.v = m_dot_8                                # m_dot_8
        self.m_dot_9.v = m_dot_9                                # m_dot_9
        self.f1.v = m_dot_2 / (m_dot_2 + m_dot_3)              # f_1
        self.f2.v = m_dot_4 / (m_dot_4 + m_dot_5)              # f_2
        self.f3.v = m_dot_6 / (m_dot_6 + m_dot_7)              # f_3
        self.f4.v = m_dot_8 / (m_dot_8 + m_dot_9)              # f_4
